language: ruby
cache: bundler
rvm:
 - 2.3.8
 - 2.4.10
 - 2.5.8
 - 2.6.6
 - 2.7.1
 - 2.8.0-dev
 - jruby-9.1.9.0
notifications:
  email:
    recipients:
    - kigster@gmail.com
    on_success: change
    on_failure: always
script:
  - gem update --system
  - gem install bundler  
  - bundle exec rspec --format=documentation
  - bundle exec rubocop
after_success:
  - bundle exec codeclimate-test-reporter
